-- Таблица пользователей (USERS)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    contact VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица ролей (USER_ROLES)
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    roles VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, roles),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Таблица дней рождения (BIRTHDAYS)
CREATE TABLE birthdays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    contact VARCHAR(255),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Индексы для birthdays
CREATE INDEX idx_birthday_date ON birthdays (date);
CREATE INDEX idx_birthday_user ON birthdays (user_id);

-- Таблица поздравлений (GREETINGS) — fixed column name to "user_id" (matches @JoinColumn)
CREATE TABLE greetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    media_url VARCHAR(500),
    is_public BOOLEAN DEFAULT FALSE,
    likes_count INT DEFAULT 0,
    user_id BIGINT NOT NULL,  -- Fixed: user_id instead of owner_id
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Индексы для greetings
CREATE INDEX idx_greeting_public_likes ON greetings (is_public, likes_count);
CREATE INDEX idx_greeting_user ON greetings (user_id);  -- Fixed name

-- Связующая таблица лайков (GREETING_LIKES)
CREATE TABLE greeting_likes (
    greeting_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (greeting_id, user_id),
    FOREIGN KEY (greeting_id) REFERENCES greetings(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_like_user ON greeting_likes (user_id);